# 
control_dt: 0.02

msg_type: "hg"     # "hg" or "go"
imu_type: "pelvis"    # "torso" or "pelvis"

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"

# policy_path: "deploy/pre_train/g1/motion.pt"
policy_path: "simulation/legged_gym/logs/g1_walk_phase/exp0/traced/exp0-3200-jit.pt"

leg_joint2motor_idx: [0, 1, 2, 3, 4, 5, 
                      6, 7, 8, 9, 10, 11]

kps: [200, 150, 150, 200, 20, 20, 
      200, 150, 150, 200, 20, 20]

kds: [5, 5, 5, 5, 4, 4, 
      5, 5, 5, 5, 4, 4]

default_angles: [-0.4,  0.0,  0.0,  0.8, -0.35, 0.0,  
                 -0.4,  0.0,  0.0,  0.8, -0.35, 0.0]

arm_waist_joint2motor_idx: [12, 13, 14, 
                            15, 16, 17, 18, 19, 20, 21, 
                            22, 23, 24, 25, 26, 27, 28]

arm_waist_kps: [300, 300, 300,
                40, 40, 40, 40, 20, 20, 20,
                40, 40, 40, 40, 20, 20, 20]

arm_waist_kds: [5, 5, 5, 
                10, 10, 10, 10, 1, 1, 1,
                10, 10, 10, 10, 1, 1, 1]

arm_waist_target: [0, 0, 0,
                   0., 0., 0, 0., 0, 0, 0,
                   0., 0., 0, 0., 0, 0, 0]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.5
# cmd_scale: [2.0, 2.0, 0.25]
num_actions: 21
num_obs: 853

# max_cmd: [0.8, 0.5, 1.57]
